config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  RATINGS = (0..5).to_a
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: RATINGS }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<div class="card">
  <h4 class="card-header"><%= restaurant.name %></h4>
  <div class="card-body">
    <ul>
      <li>
        <p>Address: <span><%= restaurant.address %></span></p>
        <p>Phone Number: <span><%= restaurant.phone_number %></span></p>
        <p>Category: <span><%= restaurant.category %></span></p>
      </li>
    </ul>
  </div>
</div>

app/views/restaurants/_simple_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container mt-5">
  <h1>Restaurants</h1>
  <div id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <%= render restaurant %>
      <p>
        <%= link_to "Show this restaurant", restaurant %>
      </p>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
<h1 class="mb-4">Create a restaurant</h1>
<%= render "simple_form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <%= render @restaurant %>
  <div class="mt-4">
    <p><strong>Reviews</strong></p>
    <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item"><%= review.content %> - <%= review.rating %></li>
      <% end %>
    </ul>
    <br>
    <%= link_to "Back to list", restaurants_path %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container mt-5">
<h1 class="mb-4">Post a review</h1>
<%= simple_form_for [@restaurant,@review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::RATINGS %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>